version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docarizedhomefurniture-php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - DB_HOST=my-sql-server
      - DB_PORT=3306
      - DB_DATABASE=home_furniture
      - DB_USERNAME=root
      - DB_PASSWORD=dee
    depends_on:
      - my-sql-server
    command: php artisan serve --host=0.0.0.0 --port=8000

# # Apache2 Web Server
#   apache:
#     image: php:8.0-apache
#     container_name: docarizedhomefurniture-apache
#     volumes:
#       - .:/var/www/html
#       - ./apache2.conf:/etc/apache2/sites-available/000-default.conf
#     ports:
#       - "80:80"  # Expose port 80 for HTTP traffic
#     depends_on:
#       - php

# Mysql
  my-sql-server:
    image: mysql:8.0
    container_name: docarizedhomefurniture-my-sql-server-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dee
      MYSQL_DATABASE: home_furniture
      MYSQL_USER: dee
      MYSQL_PASSWORD: dee
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: docarizedhomefurniture-redis-1
    ports:
      - "6379:6379"

volumes:
  db_data:
